version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge